import { Category, Product, Feature, SeasonalTheme } from './types';

export const BUSINESS_INFO = {
  name: "Dollar Delight LTD",
  tagline: "Wetaskiwin's first craft, gift & hobby dollar store",
  description: "From cozy yarn and DIY kits to notebooks and seasonal decor — all at prices that make you smile.",
  phone: "780-335-9678",
  phoneFormatted: "(780) 335-9678",
  phoneClean: "7803359678",
  email: "sanboss711@gmail.com",
  location: "Wetaskiwin, Alberta, Canada",
  trustTag: "Fun finds. Creative ideas. Prices that make you smile.",
};

export const CATEGORIES: Category[] = [
  {
    id: "yarn-crafts",
    name: "Yarn & Crafts",
    icon: "🧶",
    tagline: "Yarn & Crafts",
    description: "Cozy yarn, craft supplies, and everything you need to bring your ideas to life.",
    image: "https://images.unsplash.com/photo-1584992236310-6edddc08acff?auto=format&fit=crop&w=800&q=80",
    popularItems: ["Soft Chenille Yarn", "Crochet Hooks", "Embroidery Floss", "Felting Supplies"],
    color: "from-amber-400 to-amber-500",
    badge: "Community Favorite",
  },
  {
    id: "diy-kits",
    name: "DIY Kits",
    icon: "🎨",
    tagline: "DIY Kits",
    description: "Fun, creative kits for makers of all ages.",
    image: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=800&q=80",
    popularItems: ["Painting By Numbers", "Woodcraft Projects", "Clay Sculpting Kits", "Mosaic Coasters"],
    color: "from-teal-400 to-teal-600",
    badge: "All Ages",
  },
  {
    id: "stationery-notebooks",
    name: "Stationery & Notebooks",
    icon: "📓",
    tagline: "Stationery & Notebooks",
    description: "Cute notebooks, writing supplies, and everyday essentials.",
    image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=800&q=80",
    popularItems: ["Pastel Spiral Journals", "Gel Pens & Highlighters", "Washi Tapes", "Planner Stickers"],
    color: "from-rose-400 to-rose-500",
    badge: "Study & Journaling",
  },
  {
    id: "gifts-goodies",
    name: "Gifts & Goodies",
    icon: "🎁",
    tagline: "Gifts & Goodies",
    description: "Affordable gift ideas for birthdays, celebrations, and just because.",
    image: "https://images.unsplash.com/photo-1513885535751-8b9238bd345a?auto=format&fit=crop&w=800&q=80",
    popularItems: ["Decorative Gift Bags", "Scented Accents", "Novelty Keepsakes", "Celebration Wraps"],
    color: "from-yellow-400 to-amber-600",
    badge: "Great Values",
  },
  {
    id: "seasonal-decor",
    name: "Seasonal Decor",
    icon: "🍂",
    tagline: "Seasonal Decor",
    description: "Refresh your space with fun seasonal decorations and festive finds.",
    image: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=800&q=80",
    popularItems: ["Seasonal Garlands", "Festive Centerpieces", "Door Wreaths & Ribbons", "Holiday Ornaments"],
    color: "from-orange-400 to-amber-500",
    badge: "Rotates Year-Round",
  },
  {
    id: "hobby-fun",
    name: "Hobby & Fun",
    icon: "🧸",
    tagline: "Hobby & Fun",
    description: "Discover supplies and little treasures for your favorite hobbies.",
    image: "https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?auto=format&fit=crop&w=800&q=80",
    popularItems: ["Model Kits", "Board Games & Puzzles", "Beading & Jewelry Wire", "Sculpting Tools"],
    color: "from-emerald-400 to-teal-600",
    badge: "Fun & Leisure",
  },
];

export const FEATURED_PRODUCTS: Product[] = [
  {
    id: "sample-1",
    name: "Cozy Chenille Yarn",
    category: "Yarn & Crafts",
    shortDescription: "Plush, cloud-soft velvet touch yarn suitable for chunky blankets, amigurumi, and scarves.",
    fullDescription: "An ultra-soft bulky chenille yarn that knits and crochets with ease. Gentle on the hands and available in warm pastels and rich earth tones.",
    examplePrice: "$3.50",
    image: "https://images.unsplash.com/photo-1606760227091-3dd870d97f1d?auto=format&fit=crop&w=600&q=80",
    tag: "Crafter Favorite",
    isPopular: true,
  },
  {
    id: "sample-2",
    name: "Mini DIY Craft Kit",
    category: "DIY Kits",
    shortDescription: "Complete starter kit packed with pre-cut wooden pieces, safe pigments, and easy brush.",
    fullDescription: "A delightful weekend craft project for adults and kids alike. Includes unfinished wooden shapes, acrylic paint pots, and detailed instructions.",
    examplePrice: "$4.00",
    image: "https://images.unsplash.com/photo-1560421683-680b93811a22?auto=format&fit=crop&w=600&q=80",
    tag: "Weekend DIY",
    isPopular: true,
  },
  {
    id: "sample-3",
    name: "Cute Spiral Notebook",
    category: "Stationery & Notebooks",
    shortDescription: "Sturdy hardcover journal with high-opacity lined paper and cheerful artistic print.",
    fullDescription: "Durable wire-bound notebook with thick 80gsm paper to prevent ink bleeding. Great for grocery lists, gratitude notes, sketching, and study notes.",
    examplePrice: "$2.25",
    image: "https://images.unsplash.com/photo-1531346878377-a5be20888e57?auto=format&fit=crop&w=600&q=80",
    tag: "Everyday Essential",
  },
  {
    id: "sample-4",
    name: "Seasonal Decorative Garland",
    category: "Seasonal Decor",
    shortDescription: "Charming wooden bead & seasonal accent garland to drape along mantels or doorways.",
    fullDescription: "Hand-strung decorative garland featuring warm wooden beads, rustic twine tassels, and festive accents that make any room feel instantly inviting.",
    examplePrice: "$3.00",
    image: "https://images.unsplash.com/photo-1512496015851-a90fb38ba796?auto=format&fit=crop&w=600&q=80",
    tag: "Seasonal Find",
    isPopular: true,
  },
  {
    id: "sample-5",
    name: "Creative Sticker Set",
    category: "Stationery & Notebooks",
    shortDescription: "Multi-sheet pack of cute die-cut vinyl stickers for planners, water bottles, and cards.",
    fullDescription: "Dozens of colorful illustrated stickers with matte finishes. Perfect for scrapbooking, customizing notebooks, gift wrap accents, or rewarding little helpers.",
    examplePrice: "$1.75",
    image: "https://images.unsplash.com/photo-1589384267710-7a25a5892556?auto=format&fit=crop&w=600&q=80",
    tag: "Pocket Friendly",
  },
  {
    id: "sample-6",
    name: "Paint & Brush Kit",
    category: "DIY Kits",
    shortDescription: "Vibrant acrylic paint set with 6 blendable tubes and two fine-detail craft brushes.",
    fullDescription: "High-pigment student-grade acrylic paint set offering smooth coverage on canvas, wood, paper, and terracotta. Quick-drying and water-soluble.",
    examplePrice: "$3.75",
    image: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=600&q=80",
    tag: "Art Supplies",
  },
  {
    id: "sample-7",
    name: "Gift Bag & Tissue Set",
    category: "Gifts & Goodies",
    shortDescription: "Premium patterned gift bag with matching ribbon handles and 3 sheets of coordinating tissue.",
    fullDescription: "Make gift-giving effortless! Heavyweight printed gift bag with sturdy cord handles and vibrant tissue sheets ready for birthday and celebration gifts.",
    examplePrice: "$2.00",
    image: "https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=600&q=80",
    tag: "Gift Wrapping",
  },
  {
    id: "sample-8",
    name: "Kids Craft Activity Kit",
    category: "Hobby & Fun",
    shortDescription: "Hands-on activity set featuring colorful felt, glitter foam stickers, and pipe cleaners.",
    fullDescription: "Spark your child's imagination with an all-in-one tactile craft box. Safe, non-toxic materials designed for creative afternoon play and school projects.",
    examplePrice: "$4.50",
    image: "https://images.unsplash.com/photo-1508873696983-2df5293cb32b?auto=format&fit=crop&w=600&q=80",
    tag: "Family Craft",
    isPopular: true,
  },
];

export const WHY_CHOOSE_US: Feature[] = [
  {
    id: "affordable-finds",
    title: "Affordable Finds",
    description: "Creative, useful, and fun products without the big price tag.",
    icon: "Sparkles",
    bgGradient: "bg-amber-50 text-amber-700 border-amber-200",
    accentColor: "bg-amber-500",
  },
  {
    id: "creative-inspiration",
    title: "Creative Inspiration",
    description: "Find something that sparks your next project or hobby.",
    icon: "Palette",
    bgGradient: "bg-teal-50 text-teal-700 border-teal-200",
    accentColor: "bg-teal-600",
  },
  {
    id: "something-new",
    title: "Something New to Discover",
    description: "Explore a changing selection of crafts, gifts, stationery, and seasonal treasures.",
    icon: "Compass",
    bgGradient: "bg-rose-50 text-rose-700 border-rose-200",
    accentColor: "bg-rose-500",
  },
  {
    id: "local-welcoming",
    title: "Local & Welcoming",
    description: "A friendly local shopping destination for Wetaskiwin and the surrounding community.",
    icon: "HeartHandshake",
    bgGradient: "bg-orange-50 text-orange-700 border-orange-200",
    accentColor: "bg-orange-500",
  },
];

export const SEASONAL_THEMES: SeasonalTheme[] = [
  {
    id: "autumn-fall",
    name: "Autumn & Harvest",
    icon: "🍂",
    title: "Cozy Autumn Treasures & Warm Crafts",
    description: "Rich rustic palettes, pumpkin craft pieces, burlap ribbons, and warm knit skeins for chilly Alberta evenings.",
    highlightItems: ["Rustic Wood Signs", "Fall Burlap Garlands", "Chunky Knit Yarns", "Harvest Table Accents"],
    badgeColor: "bg-amber-500 text-white",
    image: "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "winter-holiday",
    name: "Winter & Holiday",
    icon: "❄️",
    title: "Festive Holiday Sparkle & Gift Supplies",
    description: "Glittering ribbons, seasonal gift wrappings, ornament craft bases, and cozy indoor DIY project supplies.",
    highlightItems: ["Holiday Gift Bags & Tins", "Glitter Ribbons & Bows", "DIY Ornament Blanks", "Winter Craft Kits"],
    badgeColor: "bg-teal-600 text-white",
    image: "https://images.unsplash.com/photo-1512389142860-9c449e58a543?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "spring-refresh",
    name: "Spring Renewal",
    icon: "🌷",
    title: "Fresh Spring Hues & Floral Crafts",
    description: "Bright pastel florals, decorative planter accents, Easter craft supplies, and cheerful stationery.",
    highlightItems: ["Pastel Florals & Picks", "Felt Craft Rabbits", "Mini Planters & Pots", "Spring Paper Goods"],
    badgeColor: "bg-emerald-600 text-white",
    image: "https://images.unsplash.com/photo-1490750967868-88aa4486c946?auto=format&fit=crop&w=800&q=80",
  },
  {
    id: "summer-fun",
    name: "Summer Activities",
    icon: "☀️",
    title: "Sunny Outdoor Fun & Kids Crafts",
    description: "Activity pads, colorful sidewalk chalk, outdoor party accessories, and travel-friendly hobby sets.",
    highlightItems: ["Kids Summer Craft Packs", "Colorful Chalk & Paints", "Picnic Gift Goodies", "Bead Craft Supplies"],
    badgeColor: "bg-orange-500 text-white",
    image: "https://images.unsplash.com/photo-1508873696983-2df5293cb32b?auto=format&fit=crop&w=800&q=80",
  },
];
